version: "3.7"
services:
  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
  server:
    build: back-end
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "8085:8085"
    depends_on:
      - db
    restart: on-failure
